poll_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    '''
    Model of questions that are on the main page of the site
    '''
    question_text = models.CharField('', max_length=200)
    pub_date = models.DateTimeField('')

    class Meta():
        verbose_name = 'вопрос'
        verbose_name_plural = 'Вопросы'

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Опубликовано недавно?'


class Choice(models.Model):
    '''
    Question answer model
    '''
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField('Варианты', max_length=200)
    votes = models.IntegerField('Кол-во голосов', default=0)

    class Meta():
        verbose_name_plural = 'Варианты ответов'

    def __str__(self):
        return self.choice_text
    

class RightAnswerExplanation(models.Model):
    '''
    Explanation of the correct answer
    '''
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_explanation = models.TextField('')

    class Meta():
        verbose_name = 'Пояснение к правильному ответу'

    def __str__(self):
        return self.answer_explanation

polls/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db.models import F
from django.utils import timezone
from .models import Choice, Question, RightAnswerExplanation


def index(request):
    '''Generates questions and choices on the main page with pagination'''
    question_list = Question.objects.order_by('-pub_date')
    paginator = Paginator(question_list, 4)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'polls/post/index.html',
                 {'page': page,  'posts': posts})    


class ResultsView(generic.DetailView):
    '''Generates result page after user vote'''
    model = Question
    template_name = 'polls/post/results.html'


def vote(request, question_id):
    '''Processes the user's vote'''
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return HttpResponseRedirect(reverse('polls:index'))
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', 
                                    args=(question.id,)))

polls/templates/pagination.html
<div class='pagination'>
  <span class='step_links'>
    {% if page.has_previous %}
      <a href='?page={{page.previous_page_number}}'>Предыдущая</a>
    {% endif %}
    <span class='current'>
      Страница {{ page.number }} из {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
      <a href='?page={{ page.next_page_number }}'>Следующая</a>
    {% endif %}
  </span>
</div>

polls/templates/polls/base.html
{% load static %}
<!doctype html>
<html>
 <head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
  <title>{% block title %}{% endblock %}</title>
 </head>
 <body link='#00ADFF' vlink='#00ADFF' alink='white'>
  <div class='page'>
  <h1 class='title'>А что ты знаешь о космосе дружок?</h1>
  {% block content %}
  {% endblock %}
  </div>
 </body>
</html>

polls/templates/polls/post/index.html
{% extends "polls/base.html" %}
{% block title %}Опросник{% endblock %}
{% block content %}
 {% if posts %}
   {% for question in posts %}
	<div class='question_block'>
     <div class='question'>
 	  <h3>{{ question.question_text }}</h3>
     </div>
     <form action="{% url 'polls:vote' question.id %}" method="post">
      {% csrf_token %}
      {% for choice in question.choice_set.all %}
       <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
       <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
      {% endfor %}
      <input type="submit" value="Проголосовать">
     </form>
     <div class='date'>{{ question.pub_date }}</div>
	</div>
   {% endfor %}
 {% else %}
  <p>В данный момент нет доступных опросов</p>
 {% endif %}
 <p>{% include 'pagination.html' with page=posts %}</p>
{% endblock %}

polls/templates/polls/post/results.html
{% extends "polls/base.html" %}
{% block content %}
{% load polls_tags %}
<h2>{{ question.question_text }}</h2>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} голос{{ choice.votes|plural }}</li>
{% endfor %}
</ul>
{% for answer in question.rightanswerexplanation_set.all %}
   <p>{{ answer.answer_explanation|markdown }}</p>
{% endfor %}
<a class='link' href="{% url 'polls:index' %}" title="Возвращает на главную">Вернуться к опросам</a>
{% endblock %}